### PR TITLE
Fix: Blog Link incorrect in Doc Header

### LINKED ISSUE #1065: Blog Link incorrect in Doc Header
In the doc: [https://docs.ploomber.io/](https://docs.ploomber.io/en/latest/get-started/quick-start.html), the Blog link in the header section isn't correct

Currently: https://ploomber.io/

Should be: https://ploomber.io/blog

Please update the one with the correct link

Screenshot 2023-01-04 at 10 53 09 PM

### PR DESCRIPTION
**Pull request by tonykploomber**
## Describe your changes
Fix blog link incorrect in doc

## Issue ticket number and link
Closes #1065 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by tonykploomber** [comment]
I was not able to verify the change on local because of https://github.com/ploomber/ploomber/issues/1064

However, this PR still can be merged if any reviewer can validate the change.

**Comment by tonykploomber** [comment]
Either @yafim or @neelasha23 can help review this!

**Comment by idomic** [comment]
Next time just add them as reviewers (top right).
Also, when commenting closes #issue number, no need to comment on the issue, it's linked automatically.

**Comment by tonykploomber** [comment]
> Next time just add them as reviewers (top right). Also, when commenting closes #issue number, no need to comment on the issue, it's linked automatically.

Seems I can't add them as reviewers now, probably I can't do that until my first PR gets merged?

**Comment by idomic** [comment]
Possible.
Anyway please make sure it works as expected locally?

**Comment by tonykploomber** [comment]
Thanks for the help Ido!
I was able to resolve the blocking issue by [this](https://github.com/ploomber/ploomber/issues/1064#issuecomment-1405966777) 

This is the preview on the local. Looks good to me now.


https://user-images.githubusercontent.com/123580782/215002541-90345caf-4155-4764-ae10-00e7963804e3.mov

**Comment by idomic** [comment]
Nice job!

**Pull request merged**
