### PR TITLE
improve readme getting started

### LINKED ISSUE #940: readme improvements
Our README has too many options and people get lost. It should be clear how to get started.

I think it should only give two options: running the onboarding tutorial locally or taking them to the first tutorial.

and we should replace this with a larger button since people don't see it:

image

### PR DESCRIPTION
**Pull request by grnnja**
## Issue ticket number and link
Closes #940

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@edblancas thoughts on the link? Maybe a button will be more visible. Also we might want to do something with the top binder button.

**Comment by edublancas** [comment]
yeah, let's add a button. You can copy this and manually edit it to change the label. put something like "Open in JupyterLab" https://github.com/ploomber/ploomber/blob/master/_static/get-started.svg

I think we can get rid of the binder button

**Comment by grnnja** [comment]
Updated!

**Review by idomic — APPROVED** [review]
lgtm, nice job!

**Pull request merged**
