### PR TITLE
added branch filter for CI and proper documentation

### LINKED ISSUE #820: CI duplicate executions
The CI currently have 2 flags:
on:
push:
pull_request:

We should make sure it doesn't execute twice, creating a resources bottleneck.

### PR DESCRIPTION
**Pull request by Wxl19980214**
## Describe your changes
added branch filter, updated contribute.md

## Issue ticket number and link
Closes #820 #954 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by Wxl19980214** [comment]
Do we need to give credits to the author of ok-to-test?

**Comment by edublancas** [comment]
> Do we need to give credits to the author of ok-to-test?

let's add the link to the project if you have it handy

**Comment by edublancas** [comment]
mark the PR as ready for review when ready

**Comment by Wxl19980214** [comment]
@edublancas ready to be merged

**Review by idomic — APPROVED** [review]
lgtm

**Comment by idomic** [comment]
ok-to-test sha=9d3d284

**Pull request merged**
