### PR TITLE
Prioritized cell injection

### LINKED ISSUE #902: Injecting parameters when the same notebook appears more than once
To inject cells manually, users can run:

```
ploomber nb --inject
```

However, if the same source appears more than once. Ploomber will arbitrarily select one of the tasks and inject those parameters. Making it impossible to inject the parameters from other tasks that use the same template. Here's an example:

```yaml
tasks:
  - source: template.ipynb
     name: task-a
     product: report-a.ipynb
     params:
       some_param: a

  - source: template.ipynb
     name: task-b
     product: report-b.ipynb
     params:
       some_param: b
```

If we execute:

```
ploomber nb --inject
```

`template.ipynb` will have `some_param=b`, and there is no way to tell Ploomber to inject `some_param=a`.

We need the user to tell us which set of parameters they want to inject. I'm still unsure what's the simplest way (it has to be simple since this will be typed in the terminal). One approach I can think of is to add a new CLI argument (I'll call it `--priority` now for lack of a better name)

Example:

```
ploomber nb --inject --priority task-a
ploomber nb --inject --priority task-b
```

Since it might be that two or more notebooks are used as templates, `--priority` should be allowed to appear several times:

```
ploomber nb --inject --priority task-a --priority task-c
```

However, we'd need to validate that the values passed do not correspond to the same task. For example, this should throw an error:

```
ploomber nb --inject --priority task-a --priority task-b
```

(I'm not a fan of this approach so I'll keep thinking about what the best API is, suggestions welcome!)

Furthermore, we should throw a warning explaining to the user that since `template.ipynb` appears more than once, only one set of parameters will be visible. Something like:

> `template.ipynb` appears more than once in your pipeline, the parameters from `task-b` will be injected, to inject the parameters of another task, pass: `ploomber nb --inject --priority {task-name}`

### PR DESCRIPTION
**Pull request by yafimvo**
## Describe your changes

Use `setup.cfg` to set which parameters to inject.

setup.cfg
```
[ploomber]
entry-point = pipeline.yaml
inject-priority = task-a
```

pipeline.yaml
```
tasks:
    - source: template_a.ipynb
      name: task-a
      product: output/template-a.ipynb
      params:
        some_param: param-a

    - source: template_a.ipynb
      name: task-a-suffix
      product: output/template-a-suffix.ipynb
      params:
        some_param: param-a-suffix

    - source: template_b.ipynb
      name: task-b
      product: output/template_b.ipynb
      params:
        some_param: param-b

    - source: template_b.ipynb
      name: task-b-suffix
      product: output/template-b-suffix.ipynb
      params:
        some_param: param-b-suffix
```

Use wildcards to inject multiple parameters (*)

config.cfg
```
[ploomber]
entry-point = pipeline.yaml
inject-priority = *-suffix
```

This PR is based on [PR 981](https://github.com/ploomber/ploomber/pull/981) and [PR 985](https://github.com/ploomber/ploomber/pull/985)

## Issue ticket number and link
Closes #902 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@yafimvo here I see there are some unit tests that are failing.

**Comment by edublancas** [comment]
I still need to test this, but I don't see any updates to the documentation. has this been documented?

**Comment by yafimvo** [comment]
Since it was part of the `setup.cfg` file, I updated the changelog. Where should I add this documentation?

**Comment by edublancas** [comment]
please add the docs at the bottom of this section: https://docs.ploomber.io/en/latest/get-started/basic-concepts.html#the-cell-injection-process

**Review by edublancas — APPROVED** [review]

**Pull request merged**
