### PR TITLE
Add highlighting to the anchored section

### LINKED ISSUE #773: animation after opening docs
When using the search feature, users might be directed to specific sections in the documentation. For example, if search for "schedule", the top [result is this](https://docs.ploomber.io/en/latest/deployment/batch.html#scheduling).

When clicking on it, the page scrolls down to the "Scheduling" section, however, it isn't clear to a user that such section is the one they should pay attention to. It'd better have some animation to draw attention to it, I've seen this on other websites.

### PR DESCRIPTION
**Pull request by Prathamesh010**
## Describe your changes
Adds highlighting for anchor  section

https://user-images.githubusercontent.com/41731424/193464713-3d3e0604-c9e2-4194-bc88-3626d4aa2d5c.mp4

## Issue ticket number and link
Closes #773

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by edublancas** [comment]
@RodolfoFerro

**Comment by edublancas** [comment]
@Prathamesh010 this looks good! is there any way to achieve the same effect when using the search bar?

**Comment by Prathamesh010** [comment]
It works for the search bar too. 
It's not visible on this branch because the search redirects to `docs.ploomber.io` instead of the local host.

**Comment by edublancas** [comment]
got it! can you rebase? there's a conflict with the doc/_static/css/custom-theme.css file

**Comment by Prathamesh010** [comment]
The branch is rebased.

**Comment by edublancas** [comment]
thanks for your contribution!

**Pull request merged**
