### PR TITLE
fix test_code_highlight adding what was missing to the end of the line

### LINKED ISSUE #1062: pygments breaking a test
pygments 2.14 is breaking our CI. I added a [quickfix](https://github.com/ploomber/ploomber/blob/a9d7653c20d5d638461c869ba3a3182162569d34/tests/io_mod/test_terminalwriter.py#L306) since I verified that this failure is not affecting anything critical (it's just terminal output formatting). I think this is best than pinning pygments since pining the version is worst as it'll increase the complexity of installing the package.

This is some ASCII code stuff, and I'm unsure why the pygments update is behaving in this way, here's the error:

```
===================================================================================== FAILURES ======================================================================================
________________________________________________________________ test_code_highlight[with markup and code_highlight] ________________________________________________________________

has_markup = True, code_highlight = True, expected = '{kw}assert{hl-reset} {number}0{hl-reset}\n'
color_mapping = <class 'io_mod.test_terminalwriter.color_mapping.<locals>.ColorMapping'>

    @pytest.mark.parametrize(
        ("has_markup", "code_highlight", "expected"),
        [
            pytest.param(
                True,
                True,
                "{kw}assert{hl-reset} {number}0{hl-reset}\n",
                id="with markup and code_highlight",
            ),
            pytest.param(
                True,
                False,
                "assert 0\n",
                id="with markup but no code_highlight",
            ),
            pytest.param(
                False,
                True,
                "assert 0\n",
                id="without markup but with code_highlight",
            ),
            pytest.param(
                False,
                False,
                "assert 0\n",
                id="neither markup nor code_highlight",
            ),
        ],
    )
    def test_code_highlight(has_markup, code_highlight, expected, color_mapping):
        f = io.StringIO()
        tw = terminalwriter.TerminalWriter(f)
        tw.hasmarkup = has_markup
        tw.code_highlight = code_highlight
        tw._write_source(["assert 0"], lexer='py')

>       assert f.getvalue().splitlines(keepends=True) == color_mapping.format(
            [expected])
E       AssertionError: assert ['\x1b[94mass...[39;49;00m\n'] == ['\x1b[94mass...[39;49;00m\n']
E         At index 0 diff: '\x1b[94massert\x1b[39;49;00m \x1b[94m0\x1b[39;49;00m\x1b[90m\x1b[39;49;00m\n' != '\x1b[94massert\x1b[39;49;00m \x1b[94m0\x1b[39;49;00m\n'
E         Use -v to get more diff
```

### PR DESCRIPTION
**Pull request by lbellomo**
## Describe your changes

Investigating why the new version adds `"\x1b[90m\x1b[39;49;00m"` with the pygments 2.14 I came to [this](https://github.com/pytest-dev/pytest/issues/10630) similar pytests issue with the same problem. The solution is to add this to the test.

## Issue number

Closes #1062

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://ploomber--1138.org.readthedocs.build/en/1138/

### CODE REVIEW

**Comment by edublancas** [comment]
hi @lbellomo thanks for your contribution!

I see the CI is failing. this is due to an error unrelated to this PR, I opened and assigned https://github.com/ploomber/ploomber/issues/1139, once that's fixed, I'll ping you so you can re-run the CI and we can merge this

**Comment by lbellomo** [comment]
I see that the readme links to badge are broken and that's why [another action](https://github.com/ploomber/ploomber/actions/runs/6836377132/job/18646532359?pr=1138) fails. I can fix that in another PR.

**Comment by edublancas** [comment]
@lbellomo can you merge from the main branch? that should fix the CI

**Comment by lbellomo** [comment]
> @lbellomo can you merge from the main branch? that should fix the CI

done

**Comment by edublancas** [comment]
thanks!

**Pull request merged**
