### PR TITLE
Update basic-concepts.rst

### PR DESCRIPTION
**Pull request by balapriyac**
## Describe your changes
- Fix an inadvertent typo (redundant 'out' towards the end)
- Introduce sentence breaks for easier parsing
- For example, \<content\> reads better than (eg., <content>)
- See \<this-guide\> reads better than _Click here_ (updated one instance)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Review by idomic — APPROVED** [review]
Nice job!

**Comment by balapriyac** [comment]
> Nice job!

Hi Ido,
I have a query regarding the phrasing of:
> if you `ploomber build` that command again, only tasks whose source code has changed are executed.
We run `pipeline.yaml` with `ploomber build`. Would rephrasing it to the following make sense?
> if you run `ploomber build` again, only tasks whose source code has changed are executed.

**Comment by idomic** [comment]
> Hi @idomic,
> 
> I have a query regarding the phrasing of:
> 
> > if you `ploomber build` that command again, only tasks whose source code has changed are executed.
> 
> After configuring the tasks to be run in the `pipeline.yaml` file, we run the command: `ploomber build`.
> 
> Would rephrasing the above-quoted sentence to the following make sense?
> 
> > if you run `ploomber build` again, only tasks whose source code has changed are executed.

Yes that does make sense

**Comment by idomic** [comment]
@balapriyac let's fix this one above too?

**Comment by balapriyac** [comment]
Sure @idomic, shall fix it right away.

**Review by idomic — APPROVED** [review]
lgtm.
Nice work!

**Comment by idomic** [comment]
ok-to-test sha=bc6786e

**Pull request merged**
