### PR TITLE
fixes binder config

### PR DESCRIPTION
**Pull request by AnirudhVIyer**
## Describe your changes
test binder badge

## Issue number

Closes #1118 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://ploomber--1121.org.readthedocs.build/en/1121/

### CODE REVIEW

**Comment by edublancas** [comment]
still failing, I think the problem was this: https://github.com/ploomber/ploomber/commit/cdd078a55f0768a27e3e245ab9b08da6df9874f4

you don't have to list all ploomber dependencies in the environment.yml, you can just do `-e .` and this will install ploomber + all the dependencies: https://github.com/ploomber/jupysql/blob/ece54c19cb619b403592b96cd6ff81c0f2c79c87/environment.yml#L25

**Comment by AnirudhVIyer** [comment]
@edublancas  binder 

> still failing, I think the problem was this: [cdd078a](https://github.com/ploomber/ploomber/commit/cdd078a55f0768a27e3e245ab9b08da6df9874f4)
> 
> you don't have to list all ploomber dependencies in the environment.yml, you can just do `-e .` and this will install ploomber + all the dependencies: https://github.com/ploomber/jupysql/blob/ece54c19cb619b403592b96cd6ff81c0f2c79c87/environment.yml#L25

Yeah i think pygraphviz was the issue, have removed it and running now

**Comment by AnirudhVIyer** [comment]
@edublancas  checked the latest binder build. It is successful!

**Comment by AnirudhVIyer** [comment]
@edublancas made the change to the environment.yml file, removed the other test changes. We can merge this now.

**Review by edublancas — APPROVED** [review]

**Pull request merged**
