### PR TITLE
Update to jupyter_server 2.11.0 API

### PR DESCRIPTION
**Pull request by marr75**
Added md5 parameter to PloomberContentsManager.get and passed it along to super calls.

## Describe your changes
Small interface changes to adapt to 2.11.0 jupyter_server changes

## Issue number
Closes https://github.com/ploomber/ploomber/issues/1144

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)

----
:books: Documentation preview :books:: https://ploomber--1145.org.readthedocs.build/en/1145/

### CODE REVIEW

**Comment by marr75** [comment]
I will add another commit to support <2.11 and >2.11

**Comment by edublancas** [comment]
@marr75 thanks for working on this!

how are you thinking of supporting both versions? if the code gets too complicated, we can just require >2.11 for the next ploomber release

**Comment by Wh1isper** [comment]
Jupyter server 2.11.0 has been removed, I'm trying to make this change compatible: https://github.com/jupyter-server/jupyter_server/pull/1367

**Comment by marr75** [comment]
I went with something simpler. Just forwarding *args and **kwargs to the super method.

**Comment by marr75** [comment]
Tested with jupyter_server 2.10 and 2.12.dev0

**Comment by marr75** [comment]
@Wh1isper thanks for the heads up, the 2.12 change ended up spurring a simpler change from me anyway!

**Comment by Wh1isper** [comment]
Glad to hear it!

**Comment by edublancas** [comment]
@marr75 thanks a lot for your contribution! there's some minor CI issue we have fix (unrelated to this change), once we fix it, we'll release this. in the meantime, you can install from git

**Comment by edublancas** [comment]
@marr75 this has been released in version 0.23.1!

**Pull request merged**
