### PR TITLE
Updated banner

### PR DESCRIPTION
**Pull request by neelasha23**
## Issue number

Closes https://github.com/ploomber/doc/issues/76

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
📚 Documentation preview 📚: https://ploomber--1156.org.readthedocs.build/en/1156/

### CODE REVIEW

**Comment by neelasha23** [comment]
The announcement feature is available only in the `pydata-sphinx-theme` and `sphinx-book-theme` : https://stackoverflow.com/questions/61798722/add-a-warning-directive-at-the-top-of-every-page-on-a-sphinx-rtd-site

Updating the theme is causing the build to fail with more errors. I have just added an `rst_prolog`. Please check if it looks ok @edublancas

**Comment by edublancas** [comment]
It'd be better to add the banner at the top of the page. above the navigation bar.

image

I remember there is an HTML file that defines the navigation bar, you can edit it and add the banner there

**Comment by neelasha23** [comment]
I tried adding a div in macros.html and it gets displays below the navigation bar. Also trying to add a content block in layout.html but I keep getting errors. Still looking into it.

**Review by edublancas — CHANGES_REQUESTED** [review]
please center the text and make the font a little smaller (same size as the text in the nav bar):

image

also, a gray space appears in mobiles:

image

**Comment by neelasha23** [comment]
Addressed the comments. I also noticed that the announcement bar and the navigation bar were moving when scrolling the page. Have also fixed that. The space in mobile also seems to be fixed:

Screenshot_20240219-152558_Samsung Internet

@edublancas

**Review by edublancas — APPROVED** [review]

**Pull request merged**
