### PR TITLE
Tutorial unit test

### LINKED ISSUE #799: add unit tests for onboarding tutorial
I added a small tutorial (triggered with `python -m ploomber.onboard`) but it doesn't have tests yet

### PR DESCRIPTION
**Pull request by Wxl19980214**
## Describe your changes
Added a few unit tests.

However, this is a bit different from what i thought the tests should be.  I was thinking about an end2end test testing whether a correct user action would lead to the correct next step, vice versa. 

I couldn't find a way to do that. So for now, I am mocking every external calls and other functions to make sure the entire workflow runs once and check we have corresponding outputs.

## Issue ticket number and link
Closes #799 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by edublancas** [comment]
is this ready for review? I see it's still draft

**Comment by Wxl19980214** [comment]
It is ready for review

**Comment by Wxl19980214** [comment]
@edublancas  also can you retry ok-to-test, I see it not triggering the workflow for some reason

**Comment by edublancas** [comment]
looks like the ok to test is broken, I'll merge since this is not affecting the integration tests

**Comment by Wxl19980214** [comment]
Yeah the ok-to-test is broken for some reason, I will connect with Ido on it. Might be a key error or some sort

**Pull request merged**
