### PR TITLE
Fixed Responsive bootstrap navbar issue #364

### PR DESCRIPTION
**Pull request by rehman000**
- Also added instructions on how to get into the virtual environment on windows.

### CODE REVIEW

**Comment by rehman000** [comment]
Question @edublancas why is the directory that contains `index.html`  in `.gitignore`?

image

No wonder my changes are not being committed. Is there any other file that I needed to add these changes to? Like `macros.html` or was it some other file. Given `index.html` inside the `/doc/_build/` directory will be ignored by git.

**Comment by edublancas** [comment]
yes, _build is ignored because that's the final output of the doc building process. please apply your changes to the doc source code.

in your case, the nav bar definition is here https://github.com/ploomber/ploomber/blob/master/doc/_templates/macros.html

**Comment by rehman000** [comment]
Sorry I'm a bit unfamiliar with the project directory structure. I apologize.

**Comment by edublancas** [comment]
no worries!

**Comment by rehman000** [comment]
On localhost, This is what I see for `macros.html` I can't even see a navbar. Did I mess something up? I used conda rather than pip (I doubt that matters). 

image

**Comment by edublancas** [comment]
Awesome! Merging now, thanks a lot!

**Pull request merged**
