### PR TITLE
Added tests for 3.10

### PR DESCRIPTION
**Pull request by idomic**

### CODE REVIEW

**Comment by edublancas** [comment]
ah yeah. I see them. it's because they need pygraphviz. I think let's only skip them when running on Python 3.10 and windows (so both conditions)

**Comment by idomic** [comment]
pygraphviz had issues with 3.10 so it's disabled on linux and macos as
well, so the current condition is <3.10, I've added those skips lets see if
it's passing now.

**Comment by edublancas** [comment]
got it!

**Comment by edublancas** [comment]
the CI is failing but I think it's because of the intermittent issue. lmk when it's ready for review

**Comment by edublancas** [comment]
i wanted to trigger an extra run to see the CI, will merge shortly

**Pull request merged**
