### PR TITLE
Save User Setting in Cloud set-key tests

### PR DESCRIPTION
**Pull request by dgdheeraj**
For [issue 758](https://github.com/ploomber/ploomber/issues/758):

Added pytest fixture in test_cloud.py to save the contents of config.yaml before the test and restore them after the test is completed

### CODE REVIEW

**Comment by idomic** [comment]
@dgdheeraj is this ready for review?
Also looks like some of the tests are failing, does it pass for you locally?

**Comment by idomic** [comment]
@dgdheeraj please fix the changes.
Also try running a pr without the changes, I can see the mainline branch is passing so this change might have broken these tests

**Comment by dgdheeraj** [comment]
@idomic Can you please run the workflows for the [Draft PR(https://github.com/ploomber/ploomber/pull/788)

**Comment by dgdheeraj** [comment]
@idomic Looks like the same set of tests are failing in both the PRs
```
FAILED tests/cli/test_cloud.py::test_write_pipeline_no_status_id - AssertionE...
FAILED tests/cli/test_cloud_execution.py::test_cloud_list - AssertionError: a...
FAILED tests/cli/test_cloud_execution.py::test_cloud_status - AssertionError:...
FAILED tests/cli/test_cloud_execution.py::test_cloud_products - AssertionErro...
FAILED tests/cli/test_cloud_execution.py::test_cloud_download - AssertionErro...
FAILED tests/cli/test_cloud_execution.py::test_cloud_logs - AssertionError: a...
FAILED tests/cli/test_cloud_execution.py::test_cloud_abort - AssertionError: ...
FAILED tests/cli/test_cloud_execution.py::test_cloud_data_list - assert 1 == 0
FAILED tests/cli/test_cloud_execution.py::test_cloud_data_upload_delete - ass...
```

**Comment by idomic** [comment]
It's probably related to the commit, I just committed a PR that passes so far: https://github.com/ploomber/ploomber/pull/790

**Comment by dgdheeraj** [comment]
> @dgdheeraj It's probably related to the commit, I just committed a PR that passes so far: #790
I'll try fixing it. Thanks

**Comment by dgdheeraj** [comment]
> hi @dgdheeraj, no need to make changes on your end. I checked the tests and they are failing because of a misconfiguration on the repo (you need a key that you don't have on your fork). I'll review the code later!

Thanks @edublancas 
I generated the key, ran one example on the cloud(following the documentation),
and tried running the tests locally after this completed,
All the tests were passing except  ```tests/cli/test_cloud_execution.py::test_cloud_list``` which was giving out this error
```FAILED tests/cli/test_cloud_execution.py::test_cloud_list - AssertionError: assert 3 == 7```
From my understanding so far, the test was failing initially because the output on running ```ploomber cloud list``` was empty (since I never ran anything on the cloud)
But now its failing because the number of lines from running ```ploomber cloud list``` is not 7
I have a doubt on why its checking for 7 lines since for each user, the number of lines will vary(depending on how many times they have used the cloud), the test may not run successfully for different users

**Comment by edublancas** [comment]
I reviewed the code. it looks good. one thing:

can you merge the code from the `save_user_settings` into the `write_sample_conf` fixture? I realized that those two should always go together, this will simplify things when adding more tests. once that's ready, I'll merge :)

**Comment by dgdheeraj** [comment]
> I reviewed the code. it looks good. one thing:
> 
> can you merge the code from the `save_user_settings` into the `write_sample_conf` fixture? I realized that those two should always go together, this will simplify things when adding more tests. once that's ready, I'll merge :)

Thanks for the review @edublancas 
Yeah it would simplify the code. I have merged the two fixtures like you mentioned

**Pull request merged**
