### PR TITLE
CI intermittent failure - Issue 847

### LINKED ISSUE #847: CI fails due to an intermitent test
`tests/products/test_file.py::test_task_with_client_and_metaproduct_isnt_outdated_rtrns_waiting_download[_delete_metadata]`

https://github.com/ploomber/ploomber/runs/6765722111?check_suite_focus=true

### PR DESCRIPTION
**Pull request by neelasha23**
## Describe your changes

Race condition observed in the test case `test_task_with_client_is_not_outdated_returns_waiting_download`. Replaced `unlink` with `remove` for now.

## Issue ticket number and link
Closes #847  

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@neelasha23 I think it still persists? https://github.com/ploomber/ploomber/runs/7046876591?check_suite_focus=true

**Comment by neelasha23** [comment]
Yes it's happening for the `_edit_source_code` operation, and the change made was for `delete`. Need to check.

**Pull request merged**
