### PR TITLE
Dag shallowcopy

### PR DESCRIPTION
**Pull request by neelasha23**

### CODE REVIEW

**Comment by idomic** [comment]
@neelasha23 make sure to squash the commits

**Comment by neelasha23** [comment]
@idomic Sure. Should I do it for this PR as well , since workflows are in progress?

**Comment by idomic** [comment]
For the next ones you don’t need to do it, I just realize there's a built in mechanism in Git for that.

**Comment by neelasha23** [comment]
Ok sure. Also, I see the checks are failing again. What needs to be done for this?

**Comment by edublancas** [comment]
no worries, it's a misconfiguration on our end. merging now, thanks!

**Pull request merged**
