### PR TITLE
Fix left bar scrolling CSS

### PR DESCRIPTION
**Pull request by EddieCornelious**
#727

### CODE REVIEW

**Comment by idomic** [comment]
Thanks for contributing @EddieCornelious, works great!
Feel free to pick more open issues and joining our [slack community](https://ploomber.io/community)

**Comment by idomic** [comment]
@EddieCornelious please make sure the CI is passing, (rebasing on the master should solve this)

**Comment by EddieCornelious** [comment]
I had this solution about a week ago after using the ploomber site for a bit  (thanks to chrome dev tools). I then tried to set up the dev env on my windows laptop but failed. I'm not in the Python space. So, I wait a week and see if there is any progress and decide to fork ploomber and edit the line on github that needed to be changed. So, can you just make the change from your setup? I don't think I can pass the CI tests through github's site. Thanks.

**Comment by edublancas** [comment]
thanks for your contribution!

**Pull request merged**
