### PR TITLE
[FIX]: fixed right bar in docs for mobile view

### PR DESCRIPTION
**Pull request by siddharthmagadum16**
resolved this issue : [#366 ](https://github.com/ploomber/ploomber/issues/366#issue-1027604795)

Below are the screen snips of the right bar view.

image
image
image

### CODE REVIEW

**Comment by rehman000** [comment]
I'm kind of hyped to this (if it merges) on the deployed docs! 
https://ploomber.readthedocs.io/en/latest/

**Comment by siddharthmagadum16** [comment]
Can you please label this PR as hacktoberfest-accepted, if it is going to be reviewed afterward?  I'll surely make changes if needed in the future.

**Comment by edublancas** [comment]
sure. sorry for the delay, added the tag :)

**Comment by idomic** [comment]
@siddharthmagadum16 can you please solve the conflicts?

**Comment by siddharthmagadum16** [comment]
Sure, 
I had some a doubt while resolving conflicts.
I guess the color for reference links in the docs is change to cyan, which resulted color change of the third-column nav links as well.
Should I keep the color of these links gray or let it remain as it is (cyan) ?
image

**Comment by siddharthmagadum16** [comment]
@idomic  I have resolved the conflicts and fixed some minor issues as well.

**Comment by siddharthmagadum16** [comment]
@edublancas , I have resolved the conflicts, can my PR be reviewed?

**Comment by edublancas** [comment]
Thanks for your patience! I review it and looks pretty good, thanks a lot!

One minor detail, are there alternative icons? Having the same one for the left and side bars could be confusing. Other than that, I'm ready to merge it!

**Comment by siddharthmagadum16** [comment]
I have made the required changes.

**Comment by idomic** [comment]
Thanks @siddharthmagadum16 we're looking into it!
Please consider working on this issue as well - pretty high priority/impact https://github.com/ploomber/ploomber/issues/420

**Pull request merged**
