### PR TITLE
split integration test to 3 by OS

### LINKED ISSUE #819: python 3.6 end of life
https://endoflife.date/python

Python 3.6 ended one year ago, after adding 3.10 we should start thinking of deprecating 3.6.

### PR DESCRIPTION
**Pull request by Wxl19980214**
## Describe your changes
Simply split orignal workflow to 3

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

closes #819

### CODE REVIEW

**Comment by Wxl19980214** [comment]
Since the /ok-to-test can only work on default branch. It will run the workflow in master branch. To test this, we must merge to master first then try to submit a PR from forked repo again.

**Comment by idomic** [comment]
> Since the /ok-to-test can only work on default branch. It will run the workflow in master branch. To test this, we must merge to master first then try to submit a PR from forked repo again.

Good point!

**Comment by idomic** [comment]
@Wxl19980214 Please make sure to remove the python 3.6 workflows as well.

**Comment by Wxl19980214** [comment]
Remove 3.6 from both unit and integration tests?

**Comment by idomic** [comment]
Yes we're removing support for it since python deprecated it.

**Pull request merged**
