### PR TITLE
Create folders when using sqlite

### PR DESCRIPTION
**Pull request by fferegrino**
Addresses https://github.com/ploomber/ploomber/issues/295

### CODE REVIEW

**Comment by edublancas** [comment]
Hi, thanks for your contribution!

Can you add a few more tests?

* initializing with absolute path (you can do `Path("an/intermediate/path").resolve()`)
* initializing in-memory db (e.g., `'sqlite://'`)

reference: https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#connect-strings

Also, please run [yapf](https://github.com/google/yapf) on the code.

Thanks!

**Comment by fferegrino** [comment]
Sure thing, I meant to open this one as a draft, thanks for the feedback!

**Comment by fferegrino** [comment]
@edblancas done, added the extra tests and ran yapf on both files.

Is it necessary to cover [these too](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#uri-connections)?

**Comment by edublancas** [comment]
I just made a small change for flake8 to pass. Thanks a lot! If you want to split the tests, feel free to open another PR.

**Pull request merged**
