### PR TITLE
Telemetry remove

### PR DESCRIPTION
**Pull request by Wxl19980214**
## Describe your changes

Removed telemetry. 

Use Telemetry as a class object to pass in version, pacakge_name, and posthog api key.

We need to update posthog api_key and put it in init.py

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by Wxl19980214** [comment]
I still need to put in the api key for posthog

**Comment by edublancas** [comment]
hi @Wxl19980214 - I made a small change, I created a module so we create the telemetry instance there and import; instead of creating a new instance on each module. this will fail since I moved a few things around, please fix all the broken instances, check what I did here: https://github.com/ploomber/ploomber/pull/960/commits/2552107fc978018e4dddc7a2fe8862c3f8791f5c

**Comment by idomic** [comment]
@Wxl19980214 please patch a fix.

**Comment by Wxl19980214** [comment]
fixed. ready for review

**Comment by edublancas** [comment]
nice work!

**Pull request merged**
