### PR TITLE
Added bootstrap responsive table for videos template!  #365

### PR DESCRIPTION
**Pull request by rehman000**
Responsive_Table_Demo

### CODE REVIEW

**Comment by rehman000** [comment]
Me waiting for the tests to pass ...  

gif

**Comment by edublancas** [comment]
Thanks a lot! Sorry, I think my initial description wasn't clear. Can we get something that shows two videos side by side on monitors (and perhaps tables) but collapses them into a single column on mobile?

I found this on the [bootstrap docs](https://getbootstrap.com/docs/5.1/layout/grid/#row-columns).

e.g., monitor and tablet:

image

mobile:

image

**Comment by edublancas** [comment]
Awesome! Thanks a lot!

**Comment by rehman000** [comment]
It's done! :)

**Comment by edublancas** [comment]
Looks awesome! Thanks a lot! I just made a small change to move some videos to their corresponding section.

**Pull request merged**
