### PR TITLE
Fix Windows Python 3.10 CI issue and D3 backend Error

### LINKED ISSUE #830: 3.10 windows tests failing
CI on windows for python 3.10 is failing: https://github.com/ploomber/ploomber/runs/6708215344?check_suite_focus=true

I see it's because these tests require pygraphviz but that library doesn't work with python 3.10, perhaps we should skip them on 3.10?

### LINKED ISSUE #845: D3 backend  Error
ploomber report --> gives me an error , ValueError: Error when using d3 backend: expected a path with extension .html, but got: '/tmp/tmpmojk06x4.png', please change the extension

### PR DESCRIPTION
**Pull request by 94rain**
## Describe your changes
Skip pygraphviz-related tests for Windows Python 3.10
Fix D3 backend Error by adding `backend` as an argument

## Issue ticket number and link
Closes #830

Closes #845

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by 94rain** [comment]
https://github.com/ploomber/ploomber/runs/6924703945?check_suite_focus=true seems like an intermitent test? I rememeber seeing this but disappeared in a new run.

**Comment by idomic** [comment]
@94rain let's see, I reran.

**Comment by idomic** [comment]
@94rain I see it passed, merging for now, let's stay vigilant on this intermittent test. Can you please open an issue on it?
Also, nice job!

**Pull request merged**
