### PR TITLE
replace dependency on pygraphviz - d3 dag visualization

### PR DESCRIPTION
**Pull request by Vinay26k**
Issue: #540 
**Changes**:

1. cli/plot.py contains new backend argument to handle user custom input
2. dag/dag.py contains function `plot(... backend,....)` and based on backed available logic uses either pygraphviz or d3 html template
3. dag/plot.py added d3 dag related functions for parsing and generating output file
4. address `dag_template.html` file as new resource for generating d3 dag output file

**Note**:
 - Code refactoring is in progress

**References** :
- [d3-dag package repository](https://github.com/erikbrinkman/d3-dag)

### CODE REVIEW

**Review by edublancas — CHANGES_REQUESTED** [review]
Looking good! I just added a small comment. Please add a few tests to check the different scenarios, check out the existing tests that we have (both when invoked from the CLI and when calling `dag.plot`

**Comment by edublancas** [comment]
a few things I found:

the arrows are reversed (it should be get -> features, get -> join)

image

I tried with a larger dag and the labels don't appear:

image

just a heads up, I see this is still WIP :)

**Comment by idomic** [comment]
@Vinay26k any updates here?

**Comment by edublancas** [comment]
hey @Vinay26k , thanks for your work, we'll take it from here!

**Pull request merged**
