### PR TITLE
Added did you mean feature to `ploomber examples`

### LINKED ISSUE #805: add did you mean feature to `ploomber examples`
We should add the "did you mean?" feature when executing `ploomber examples`

```sh
 ploomber examples -n cookbook/fileclient -o fileclient
```

```txt
There is no example named "cookbook/fileclient", did you mean "cookbook/file-client"?
```

for reference: We already have this built-in in other places https://github.com/ploomber/ploomber/blob/907c5ed798354efbedc5f4cfd397179e75812ec5/src/ploomber_cli/cli.py#L17

### PR DESCRIPTION
**Pull request by aadityasinha-dotcom**
I have added a 'did you mean feature' to the `ploomber examples`.

On running the command this:-
` ploomber examples -n cookbook/fileclient -o fileclient`

The Output will be this:-

`There is no example named "cookbook/fileclient", did you mean "cookbook/file-client"?`

Resolves #805

### CODE REVIEW

**Comment by Wxl19980214** [comment]
test comment please ignore

**Comment by aadityasinha-dotcom** [comment]
@idomic can you review the changes?

**Comment by idomic** [comment]
@aadityasinha-dotcom you have CI errors.
Also we have someone already working on this issue, to what I know the PR is almost done so no need to duplicate efforts.

**Comment by aadityasinha-dotcom** [comment]
Okay, if there is any work for me you can assign me. I am ready to do it.

**Pull request closed without merging**
