### PR TITLE
Autocompleter editor

### LINKED ISSUE #893: Autocomplete editor for `pipeline.yaml`
Most of our users interact with Ploomber via a `pipeline.yaml`; which has a pre-defined [schema.](https://docs.ploomber.io/en/latest/api/spec.html#spec-api-pipeline-yaml) However, this isn't friendly for beginners who don't know the allowed values. The idea is to build a Jupyter plug-in that adds autocomplete. Note that this is a big feature, so let's go step by step and figure out things along the way.

We want to build this as a JupyterLab extension. Here's the documentation to [build extensions](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#), here's a [tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html) that shows how to build a simple extension, and here's a list of [examples.](https://github.com/jupyterlab/extension-examples)

Based on [this](https://github.com/jupyterlab/extension-examples#about-jupyterlab), it looks like JupyterLab provides re-usable components:

> Some of the higher level components that can be used are **text editors,** terminals, notebooks, interactive widgets, filebrowser, renderers for different file formats that provide access to an enormous ecosystem of libraries from different languages.

so the first thing to figure out is how to re-use the existing text editor and add the autocomplete feature. Essentially, we want something like [this](https://github.com/jupyterlab/extension-examples/tree/master/completer) but inside the text editor (not the notebook interface).

Note that a similar feature is already built-in (you we might want to look at JupyerLab's source code to get some inspiration):

image

To see it in action:

1. Create a file with .py extension on JupyterLab
2. Open the file
3. Right click on the editor window and click "Create Console for Editor"
4. Then add some Python code (e.g. "import") and hit tab

We essentially want the same thing except for files named `pipeline.yaml` and without the requirement to click on "create a console for editor".

Some tasks to get started:

- [ ] figure out how to add a custom text editor that re-uses the one that JupyterLab provides
- [ ] add an autocomplete feature (show the tooltip when pressing the tab key) with some dummy values

### PR DESCRIPTION
**Pull request by e1ha**
## Describe your changes
autocompleter extension 

## Issue ticket number and link
Closes #893

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by edublancas** [comment]
are there any setup steps involved?

**Comment by e1ha** [comment]
Run `npm i --save-dev @types/codemirror` in the autocompleter directory. Then follow the steps in the Readme.md in that directory to run the extension locally. After you get it to run locally, to open the autocompleter, open the command palette (control shift c) and type in "Text Editor". Select the text editor. This should open up an editor in a new tab. Then press tab to trigger the autocompleter. The placeholder keywords I have are `'impScience', 'impMagic', 'imply', 'life', 'living', 'lifoo', 'danger', 'danish'` so typing a substring of any of those keywords and then pressing tab will trigger the tooltip. You can also press tab to move the tooltip downwards, press enter to select the word and insert it into the text editor and click outside of the tooltip to clear the tooltip without selecting any word of the autocompleter. 

There is an issue that I need help with which is how when pressing tab, it should only be triggering the tooltip and shouldn't be increasing the spaces. In the keydown eventlistener, I've tried calling event.preventDefault(), event.stopPropagation, and event.stopImmeditatePropagation, in order to prevent this from happening but it didn't work. I also need to ensure that the text is retained after refreshing but I thought I'd get your opinions about the current UX first before continuing.

**Comment by edublancas** [comment]
running this:

```
npm i --save-dev @types/codemirror
```

gave this error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @jupyterlab/translation@^3.4.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Edu/.npm/_logs/2022-08-10T13_51_08_998Z-debug-0.log
```


ideas?

**Comment by e1ha** [comment]
I didn't come across this error. Would this help: https://stackoverflow.com/questions/44331005/npm-error-no-matching-version-found-for ?

**Comment by edublancas** [comment]
ok `npm cache clean --force` fixed it.

great, I was able to test it.

a few things: after accepting the suggestion with enter, a newline is created

```
li
fe
```

but it should be

```
life
```

also, I was expecting the arrow keys to move the suggestion on the tooltip and the ESC key to dismiss the tooltip.

to have an idea of the user experience, create a notebook and check how the autocomplete works:
image

it's triggered with tab, but other than that, the experience should be the same (ESC key and arrows)

**Comment by e1ha** [comment]
My bad, I forgot about the issue with the enter key. I asked Yafim for help since I couldn't resolve it. I will look into the jupyter notebook autocompleter.

**Comment by edublancas** [comment]
no worries. great work! I remember I tried looking at this a while ago and it seemed intimidating 😅 - this is gonna be extremely useful for our users!

**Comment by e1ha** [comment]
Yes. Just an update, but there are still two main issues: I've been trying to find a way to save the content when you press command S. I'm not completely certain you can do it for the specific class object that I'm using, so would it be fine without? Second issue is refreshing the content. When you refresh the content in the editor disappears. Other than that, I haven't found any other issues when I was testing it.  

Additionally, I used the same CSS from the jupyterlab autocompleter so would I need to add Jupyterlab's copyright notice onto our License? Not too sure since I've never done this before.

**Comment by e1ha** [comment]
Another update: for the two issues I mentioned above, I'm not sure how to solve them so I posted questions on the Jupyter Lab forum. I am awaiting a response.

**Comment by edublancas** [comment]
>Just an update, but there are still two main issues: I've been trying to find a way to save the content when you press command S. I'm not completely certain you can do it for the specific class object that I'm using, so would it be fine without? Second issue is refreshing the content. When you refresh the content in the editor disappears. Other than that, I haven't found any other issues when I was testing it.

yeah we need the save feature since users will edit files

> Additionally, I used the same CSS from the jupyterlab autocompleter so would I need to add Jupyterlab's copyright notice onto our License? Not too sure since I've never done this before.

Yes, we need to include the license. Add it at the top of the file

**Comment by e1ha** [comment]
@edublancas @idomic This PR is ready for review. I fixed the refresh and save issue I was having.

Updated instructions: 
If you haven't already, run `npm i --save-dev @types/codemirror` in the autocompleter directory. Then follow the steps in the Readme.md in that directory to run the extension locally. After you get it to run locally, to open the autocompleter, open the command palette (control shift c) and type in "Ploomber Autocompleter Editor". Select that option. This should open up a new file in a new tab. Then press Ctrl Space to trigger the autocompleter. The placeholder keywords I have are 'impScience', 'impMagic', 'imply', 'life', 'living', 'lifoo', 'danger', 'danish' so typing a substring of any of those keywords and then pressing Ctrl Space will trigger the tooltip. You can also press up or down  arrows to move the tooltip downwards, press enter to select the word and insert it into the file, and click outside of the tooltip or ESC or arrow left to clear the tooltip without selecting any word in the tooltip.

**Comment by e1ha** [comment]
For these flake8 errors can we ignore them for now? These came with the original cookiecutter files for building an extension and I don't want to make changes to them just in case.

`.\autocompleter_editor\autocompleter_editor\__init__.py:4:1: F401 '._version.__version__' imported but unused
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:9:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:10:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:11:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:13:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:14:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:15:1: F[82](https://github.com/ploomber/ploomber/runs/8130032830?check_suite_focus=true#step:7:83)1 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:16:1: F821 undefined name 'c'
.\autocompleter_editor\ui-tests\jupyter_server_test_config.py:17:1: F821 undefined name 'c'`

**Comment by e1ha** [comment]
@edublancas I've fixed all CI/CD errors. It's ready for review.

**Comment by edublancas** [comment]
I see a lot of files coming from the example you used as a starting point (for example an autocomplete_editor/README, and autocomplete_editor/setup.py). We already have those files for the current package.

I suggest deleting the ones that are not relevant, and merging the autocomplete editor in the existing package, the idea is that when a user does:

```
pip install ploomber
```

it should get both ploomber and the autocomplete package. I think most of the changes for this to work must happen in the setup.py file (essentially see how the autocomplete_editor/setup.py is configuring the extension and apply those changes to our setup.py)

**Pull request closed without merging**
