### PR TITLE
Improved CLI command suggestions

### LINKED ISSUE #618: Improve CLI command suggestions
We currently have a hardcoded list of strings to catch typos when executing a command: https://github.com/ploomber/ploomber/blob/ff808c83bc63ce8c1ae09b726f0bceeb6d9d786e/src/ploomber/cli/cli.py#L243

However, this isn't robust. pip implements it using difflib, which is part of the standard library:

https://github.com/pypa/pip/blob/5ab7c124db917625e55693773bcc224793d7ceed/src/pip/_internal/commands/help.py

### PR DESCRIPTION
**Pull request by aadityasinha-dotcom**
Improved CLI command suggestions using `difflib`
Resolves #618

### CODE REVIEW

**Comment by edublancas** [comment]
please check the CI status, the build is failing due to the flake8 linting, check out the [contributing.md](https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md) doc to learn more

**Comment by idomic** [comment]
Just to clarify, looks like it didn't pass the lint stage, try using yapf and fixing those issues:
/src/ploomber/cli/cli.py:255:80: E[50](https://github.com/ploomber/ploomber/runs/5375023774?check_suite_focus=true#step:7:50)1 line too long (131 > 79 characters)
./src/ploomber/cli/cli.py:256:80: E501 line too long (87 > 79 characters)
./src/ploomber/cli/cli.py:258:29: E128 continuation line under-indented for visual indent
./src/ploomber/cli/cli.py:264:37: E128 continuation line under-indented for visual indent
./src/ploomber/cli/cli.py:264:80: E501 line too long (82 > 79 characters)
./src/ploomber/cli/cli.py:265:37: E128 continuation line under-indented for visual indent
./src/ploomber/cli/cli.py:269:33: E128 continuation line under-indented for visual indent

**Comment by aadityasinha-dotcom** [comment]
> Just to clarify, looks like it didn't pass the lint stage, try using yapf and fixing those issues:
> /src/ploomber/cli/cli.py:255:80: E[50](https://github.com/ploomber/ploomber/runs/5375023774?check_suite_focus=true#step:7:50)1 line too long (131 > 79 characters)
> ./src/ploomber/cli/cli.py:256:80: E501 line too long (87 > 79 characters)
> ./src/ploomber/cli/cli.py:258:29: E128 continuation line under-indented for visual indent
> ./src/ploomber/cli/cli.py:264:37: E128 continuation line under-indented for visual indent
> ./src/ploomber/cli/cli.py:264:80: E501 line too long (82 > 79 characters)
> ./src/ploomber/cli/cli.py:265:37: E128 continuation line under-indented for visual indent
> ./src/ploomber/cli/cli.py:269:33: E128 continuation line under-indented for visual indent

Ok

**Comment by edublancas** [comment]
thanks for your contribution @aadityasinha-dotcom!

**Pull request merged**
