### PR TITLE
Handle exceptions in `jupyter.manager.load_dag`

### LINKED ISSUE #878: Cannot load notebooks: ModuleNotFoundError: Error processing dotted path
I have a notebook folder in ploomber project and ploomber tries to run something so I can't even load the notebook (which BTW is not referenced in pipeline.yaml in any way)

What happened? How is it possible that ploomber breaks jupyter?

Error message

```
[I 11:59:22.671 NotebookApp] [Ploomber] Requested model: work/wwf/notebooks/Enrich_Test.ipynb. Looking for DAG with root dir: /home/kuba/Projects                            
[E 11:59:22.786 NotebookApp] Uncaught exception GET /api/contents/work/wwf/notebooks/Enrich_Test.ipynb?type=notebook&_=1656064762442 (127.0.0.1)                             
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/work/wwf/notebooks/Enrich_Test.ipynb?type=notebook&_=1656064762442', version='
HTTP/1.1', remote_ip='127.0.0.1')                                                                                                                                            
    Traceback (most recent call last):                                                                                                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute                                                                            
        result = await result                                                                                                                                                
      File "/home/kuba/.local/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper                                                                              
        yielded = ctx_run(next, result)                                                                                                                                      
      File "/home/kuba/.local/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 118, in get                                                          
        model = yield maybe_future(self.contents_manager.get(                  
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 267, in get                                                                     
        self.load_dag(                                                                                                                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 193, in load_dag                                                                
        pairs = [(resolve_path(                                                       
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/jupyter/manager.py", line 196, in <listcomp>                                                                      if t.source.loc is not None]                                                  
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/sources/pythoncallablesource.py", line 130, in loc                                                        
        self._loc = self._callable_loader.get_loc()                                                                                                                          
      File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/sources/pythoncallablesource.py", line 58, in get_loc                                                     
        loc, _ = lazily_locate_dotted_path(self._primitive)                                                                                                                        File "/home/kuba/.local/lib/python3.8/site-packages/ploomber/util/dotted_path.py", line 343, in lazily_locate_dotted_path                                              
        raise ModuleNotFoundError('Error processing dotted '
    ModuleNotFoundError: Error processing dotted path 'deepsense_wwf.data_utils.copy_zipped_data': 'deepsense_wwf' appears to be a namespace package, which are not supported
[W 11:59:22.790 NotebookApp] Unhandled error          
[E 11:59:22.791 NotebookApp] {                                                                                                                                               
      "Host": "localhost:8888",                                                                                                                                              
      "Accept": "application/json, text/javascript, */*; q=0.01",                                                                                                            
      "Referer": "http://localhost:8888/notebooks/work/wwf/notebooks/Enrich_Test.ipynb",                                                                                     
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"                                                                         
    }                                                          
```

### PR DESCRIPTION
**Pull request by 94rain**
## Describe your changes
Move actual implementation of `load_dag` to `_load_dag` and handle exceptions for `_load_dag`

## Issue ticket number and link
Fixes #878 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@94rain please add some tests

**Comment by edublancas** [comment]
hint for the tests: mock `self._load_dag` and make it crash. also mock the jupyter logger. and check that there aren't any records saying "uncaught exception"

**Comment by idomic** [comment]
I think we can do it that way too.
Do you have specific exceptions you can capture? We should try avoiding the generic `Exception` when possible.

**Comment by edublancas** [comment]
> Do you have specific exceptions you can capture? 

here it makes sense to use `Exception` since we want a catch-all thing. agree it's not best practice but it'll prevent jupyter from breaking

**Comment by idomic** [comment]
Sounds good, so we're just missing the capsys on the Jupyter logs.

**Comment by 94rain** [comment]
I am still unsure how to use `PloomberContentsManager` in a jupyter serverapp. Is `app.contents_manager_class = derive_class(PloomberContentsManager)` the correct approach? Basically, I want to call the `PloomberContentsManager._load_dag` method but I am not sure how to do it with its logs tracked by jupyter.
```python
def test_load_dag_exception_handling(monkeypatch, capsys):
    app = serverapp.ServerApp()
    app.initialize(argv=[])

    # jupyter refreshes the current directory every few seconds
    # (by calling.get('')), we simulate that here
    app.contents_manager_class = derive_class(PloomberContentsManager) # try to use `PloomberContentsManager` in a jupyter serverapp
    app.contents_manager.get('')
    app.contents_manager.get('')

    cm = app.contents_manager
    mock_exception = Mock(side_effect=ValueError('known error'))
    monkeypatch.setattr(cm.log, 'exception', Mock())
    monkeypatch.setattr(cm, '_load_dag', mock_exception) # raises the exception `'JupytextContentsManager' object has no attribute 'load_dag'`.
```
When I run `monkeypatch.setattr(cm, '_load_dag', mock_exception)`, it raises the exception `'JupytextContentsManager' object has no attribute 'load_dag'`.

**Comment by edublancas** [comment]
when I wrote those tests, I was using capsys, but then I realized it was a bit annoying so I switched to mocking the function that jupyter uses to log to the console. here's a very similar test to what we need here:

https://github.com/ploomber/ploomber/blob/54c26e1885c019f4a954d3f4b37ed136cd72a2fc/tests/test_jupyter.py#L607

we need to mock the log, and mock the function that we want to crash, then we check that the right message was sent to the log. check out the test and if you still have issues, ping me @94rain

**Comment by 94rain** [comment]
Yes, I have already written a test similar to that example there:  

https://github.com/ploomber/ploomber/blob/0e8492df7e61b35d794e5927163434024865289a/tests/test_jupyter.py#L1150-L1162

Is there anything else I am still missing there?

**Comment by 94rain** [comment]
I updated the assertion here to ensure there are no other output messages: `assert cm.log.exception.call_args_list == [call(msg)]`

**Pull request merged**
